import { StyleSheet, Platform } from 'react-native';
import { COLORS, VARS } from '@/lib/constants';

const GREEN_LIGHT = '#E8F5E9';
const GREEN_BORDER = '#C8E6C9';
const GREEN_MUTED = '#66BB6A';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollContent: {
    paddingHorizontal: VARS.medium,
    paddingBottom: VARS.xlarge,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: VARS.medium,
  },
  backButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButtonSpacer: {
    width: 40,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: COLORS.text,
    flex: 1,
    textAlign: 'center',
  },
  centerContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: VARS.medium,
  },
  errorText: {
    color: COLORS.error,
    marginBottom: VARS.small,
    textAlign: 'center',
  },

  enterCodeCard: {
    backgroundColor: GREEN_LIGHT,
    borderRadius: VARS.medium,
    padding: VARS.medium,
    marginBottom: VARS.medium,
    borderWidth: 1,
    borderColor: GREEN_BORDER,
  },
  enterCodeTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.primary,
    marginBottom: 4,
  },
  enterCodeCountdown: {
    fontSize: 13,
    color: GREEN_MUTED,
    marginBottom: VARS.small,
  },
  enterCodeRow: {
    gap: VARS.small,
  },
  enterCodeInput: {
    width: '100%',
    backgroundColor: COLORS.white,
    borderRadius: VARS.xsmall,
    borderWidth: 1,
    borderColor: GREEN_BORDER,
    fontSize: 16,
    letterSpacing: 1,
    paddingVertical: VARS.small,
    paddingHorizontal: VARS.small,
    fontFamily: Platform.select({
      ios: 'Menlo',
      android: 'monospace',
      default: undefined,
    }),
  },
  applyButton: {
    width: '100%',
    backgroundColor: COLORS.primary,
    borderRadius: VARS.xsmall,
    paddingVertical: VARS.small,
    paddingHorizontal: VARS.medium,
    justifyContent: 'center',
    alignItems: 'center',
  },
  applyButtonDisabled: {
    opacity: 0.5,
  },
  applyButtonText: {
    color: COLORS.white,
    fontWeight: '700',
    fontSize: 15,
  },
  inlineError: {
    fontSize: 13,
    color: COLORS.error,
    marginTop: VARS.xxsmall,
  },
  successCard: {
    backgroundColor: GREEN_LIGHT,
    borderRadius: VARS.medium,
    padding: VARS.medium,
    marginBottom: VARS.medium,
    flexDirection: 'row',
    alignItems: 'center',
    gap: VARS.small,
    borderWidth: 1,
    borderColor: GREEN_BORDER,
  },
  successText: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: COLORS.success,
  },

  yourCodeCard: {
    backgroundColor: GREEN_LIGHT,
    borderRadius: VARS.medium,
    padding: VARS.medium,
    marginBottom: VARS.medium,
    borderWidth: 1,
    borderColor: GREEN_BORDER,
  },
  yourCodeTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.primary,
    marginBottom: 4,
  },
  yourCodeSubtext: {
    fontSize: 14,
    color: COLORS.text,
    opacity: 0.85,
    lineHeight: 20,
    marginBottom: VARS.medium,
  },
  codeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: VARS.xsmall,
    marginBottom: VARS.medium,
  },
  codeBox: {
    flex: 1,
    backgroundColor: COLORS.white,
    borderRadius: VARS.xsmall,
    paddingVertical: VARS.small,
    paddingHorizontal: VARS.medium,
    borderWidth: 1,
    borderColor: GREEN_BORDER,
  },
  codeText: {
    fontSize: 20,
    fontWeight: '700',
    color: COLORS.primary,
    letterSpacing: 2,
    fontFamily: Platform.select({
      ios: 'Menlo',
      android: 'monospace',
      default: undefined,
    }),
  },
  copyIconButton: {
    width: 48,
    height: 48,
    borderRadius: VARS.xsmall,
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  copiedLabel: {
    fontSize: 11,
    color: COLORS.primary,
    textAlign: 'center',
    marginTop: 2,
  },
  shareButtonsRow: {
    flexDirection: 'row',
    gap: VARS.xsmall,
  },
  whatsappButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: COLORS.primary,
    borderRadius: VARS.xsmall,
    paddingVertical: VARS.small,
  },
  whatsappButtonText: {
    color: COLORS.white,
    fontWeight: '700',
    fontSize: 15,
  },
  shareLinkButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: COLORS.white,
    borderRadius: VARS.xsmall,
    paddingVertical: VARS.small,
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
  shareLinkButtonText: {
    color: COLORS.primary,
    fontWeight: '700',
    fontSize: 15,
  },

  statsRow: {
    flexDirection: 'row',
    gap: VARS.xsmall,
    marginBottom: VARS.medium,
  },
  statCard: {
    flex: 1,
    backgroundColor: COLORS.white,
    borderRadius: VARS.medium,
    padding: VARS.small,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 2,
  },
  statValue: {
    fontSize: 22,
    fontWeight: '700',
    color: COLORS.primary,
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 11,
    color: COLORS.textSecondary,
    textAlign: 'center',
    lineHeight: 14,
  },

  howItWorksCard: {
    backgroundColor: COLORS.white,
    borderRadius: VARS.medium,
    padding: VARS.medium,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    elevation: 2,
  },
  howItWorksTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.text,
    marginBottom: VARS.small,
  },
  howItWorksStep: {
    flexDirection: 'row',
    gap: VARS.xsmall,
    marginBottom: VARS.xsmall,
  },
  stepNumber: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepNumberText: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.white,
  },
  stepText: {
    flex: 1,
    fontSize: 14,
    color: COLORS.text,
    lineHeight: 20,
  },
});
