import { StyleSheet } from 'react-native';
import { COLORS, VARS } from '@/lib/constants';

const CARD_RADIUS = 20;
const BANNER_GREEN = '#E8F5E9';
const BORDER = '#EEF0EE';
const MUTED_GREEN = '#4F8A56';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: VARS.xsmall,
    paddingTop: VARS.xxsmall,
    paddingBottom: VARS.xsmall,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  helpPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 22,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  helpPillText: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.text,
  },
  titleBlock: {
    paddingHorizontal: VARS.small,
    marginBottom: VARS.small,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: COLORS.text,
  },
  subtitle: {
    marginTop: 4,
    fontSize: 15,
    color: COLORS.textSecondary,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: VARS.small,
    paddingBottom: VARS.medium,
  },
  banner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: VARS.xsmall,
    backgroundColor: BANNER_GREEN,
    borderRadius: 16,
    padding: VARS.small,
    marginBottom: VARS.small,
  },
  bannerIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bannerCopy: {
    flex: 1,
  },
  bannerTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: MUTED_GREEN,
    marginBottom: 2,
  },
  bannerBody: {
    fontSize: 13,
    color: MUTED_GREEN,
    lineHeight: 18,
  },
  itemCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: CARD_RADIUS,
    borderWidth: 1,
    borderColor: BORDER,
    padding: VARS.xsmall,
    marginBottom: VARS.xsmall,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  itemThumb: {
    width: 72,
    height: 72,
    borderRadius: 14,
    backgroundColor: '#F3F4F3',
  },
  itemCopy: {
    flex: 1,
    minWidth: 0,
    marginLeft: VARS.xsmall,
    marginRight: VARS.xxsmall,
  },
  itemName: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.text,
    marginBottom: 2,
  },
  itemDescription: {
    fontSize: 13,
    color: COLORS.textSecondary,
    lineHeight: 18,
    marginBottom: 6,
  },
  itemPrice: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.primary,
  },
  stepper: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  stepperButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperMinus: {
    backgroundColor: '#F1F3F1',
  },
  stepperMinusDisabled: {
    opacity: 0.45,
  },
  stepperPlus: {
    backgroundColor: COLORS.primary,
  },
  stepperValue: {
    minWidth: 22,
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.text,
    marginHorizontal: 6,
  },
  guideRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: VARS.xsmall,
    backgroundColor: BANNER_GREEN,
    borderRadius: 16,
    padding: VARS.small,
    marginTop: VARS.xxsmall,
  },
  guideIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  guideCopy: {
    flex: 1,
  },
  guideTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: MUTED_GREEN,
    marginBottom: 2,
  },
  guideBody: {
    fontSize: 13,
    color: MUTED_GREEN,
    lineHeight: 18,
  },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: VARS.small,
    paddingHorizontal: VARS.small,
    paddingTop: VARS.small,
    backgroundColor: COLORS.white,
    borderTopWidth: 1,
    borderTopColor: BORDER,
  },
  totalLabel: {
    fontSize: 13,
    color: COLORS.textSecondary,
    marginBottom: 2,
  },
  totalValue: {
    fontSize: 26,
    fontWeight: '700',
    color: COLORS.text,
  },
  continueButton: {
    flex: 1,
    maxWidth: 220,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: COLORS.primary,
    borderRadius: 28,
    paddingVertical: 16,
    paddingHorizontal: VARS.small,
  },
  continueButtonDisabled: {
    opacity: 0.4,
  },
  continueButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.white,
  },
  emptyText: {
    fontSize: 14,
    color: COLORS.textSecondary,
    textAlign: 'center',
    marginVertical: VARS.medium,
  },
  loader: {
    marginVertical: VARS.large,
  },
  bottomSheetOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  bottomSheetDismiss: {
    flex: 1,
  },
  bottomSheetContainer: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: VARS.medium,
    borderTopRightRadius: VARS.medium,
    paddingHorizontal: VARS.medium,
    paddingTop: VARS.small,
    paddingBottom: VARS.large,
  },
  bottomSheetHandle: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: COLORS.textSecondary,
    marginBottom: VARS.small,
    opacity: 0.4,
  },
  bottomSheetTitle: {
    fontSize: VARS.medium,
    fontWeight: '700',
    color: COLORS.text,
    marginBottom: VARS.small,
    textAlign: 'center',
  },
  bottomSheetRow: {
    marginBottom: VARS.small,
  },
  bottomSheetRowTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.text,
    marginBottom: 4,
  },
  bottomSheetRowSubtitle: {
    fontSize: 14,
    color: COLORS.textSecondary,
    lineHeight: 20,
  },
  bottomSheetCloseButton: {
    marginTop: VARS.small,
    alignSelf: 'center',
    paddingVertical: VARS.xsmall,
    paddingHorizontal: VARS.large,
    borderRadius: VARS.xsmall,
    backgroundColor: COLORS.primary,
  },
  bottomSheetCloseButtonText: {
    fontSize: VARS.small,
    fontWeight: '600',
    color: COLORS.white,
  },
});
