import { StyleSheet } from 'react-native';
import { colors, radius, spacing, typography } from '@platform/shared-theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.surfaceWhite,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.md,
  },
  headerButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.surfaceWhite,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.shadow,
    shadowOpacity: 1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  headerCopy: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: spacing.sm,
  },
  headerTitle: {
    ...typography.headline,
    fontSize: 17,
  },
  headerSubtitle: {
    ...typography.body,
    fontSize: 13,
    marginTop: 2,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.xl,
  },
  summaryCard: {
    backgroundColor: colors.brandGreenSoft,
    borderRadius: radius.card,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.md,
  },
  summaryLabel: {
    ...typography.earningsLabel,
    fontWeight: '500',
  },
  summaryTotal: {
    color: colors.inkPrimary,
    fontSize: 36,
    fontWeight: '800',
    marginTop: 4,
    letterSpacing: -0.5,
  },
  summaryDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: colors.brandGreen,
    opacity: 0.18,
    marginTop: spacing.md,
    marginBottom: spacing.md,
  },
  statsRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  statColumn: {
    flex: 1,
    alignItems: 'center',
  },
  statDivider: {
    width: StyleSheet.hairlineWidth,
    alignSelf: 'stretch',
    backgroundColor: colors.brandGreen,
    opacity: 0.18,
  },
  statIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.surfaceWhite,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.sm,
  },
  statValue: {
    color: colors.inkPrimary,
    fontSize: 16,
    fontWeight: '700',
  },
  statLabel: {
    ...typography.earningsLabel,
    fontWeight: '500',
    fontSize: 11,
    textAlign: 'center',
    marginTop: 2,
  },
  sectionTitle: {
    ...typography.headline,
    fontSize: 17,
    marginTop: spacing.xl,
    marginBottom: spacing.md,
  },
  jobCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surfaceWhite,
    borderRadius: radius.card,
    paddingVertical: 14,
    paddingHorizontal: spacing.md,
    marginBottom: spacing.sm,
    shadowColor: colors.shadow,
    shadowOpacity: 1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  jobTime: {
    width: 48,
    ...typography.body,
    fontSize: 13,
    fontWeight: '600',
  },
  jobRail: {
    width: StyleSheet.hairlineWidth,
    alignSelf: 'stretch',
    backgroundColor: colors.surfaceMutedIcon,
    marginRight: spacing.md,
  },
  jobCopy: {
    flex: 1,
    paddingRight: spacing.sm,
  },
  jobTitle: {
    color: colors.inkPrimary,
    fontSize: 15,
    fontWeight: '700',
  },
  jobRoute: {
    ...typography.statusSubtext,
    marginTop: 2,
  },
  jobFare: {
    color: colors.inkPrimary,
    fontSize: 15,
    fontWeight: '700',
    marginRight: 4,
  },
  infoBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
    backgroundColor: colors.surfaceWhite,
    borderRadius: radius.card,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md,
    marginTop: spacing.md,
    shadowColor: colors.shadow,
    shadowOpacity: 1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  infoIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.surfaceMutedIcon,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoCopy: {
    flex: 1,
  },
  infoTitle: {
    color: colors.inkPrimary,
    fontSize: 14,
    fontWeight: '700',
  },
  infoBody: {
    ...typography.statusSubtext,
    marginTop: 2,
  },
  loadingWrap: {
    flex: 1,
    paddingVertical: spacing.xl,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
