import { StyleSheet } from 'react-native';
import { colors, radius, spacing, typography } from '@platform/shared-theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.surfaceWhite,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    marginLeft: spacing.lg,
    marginTop: spacing.sm,
    backgroundColor: colors.surfaceWhite,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.shadow,
    shadowOpacity: 1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  headerCopy: {
    paddingTop: spacing.sm,
    paddingBottom: spacing.md,
  },
  title: {
    ...typography.headline,
    fontSize: 28,
    fontWeight: '800',
  },
  subtitle: {
    ...typography.body,
    marginTop: 4,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.xl,
  },
  periodBar: {
    flexDirection: 'row',
    backgroundColor: colors.surfaceMutedIcon,
    borderRadius: radius.pill,
    padding: 4,
  },
  periodTab: {
    flex: 1,
    minHeight: 36,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xs,
  },
  periodTabSelected: {
    backgroundColor: colors.brandGreen,
  },
  periodTabLabel: {
    color: colors.inkSecondary,
    fontSize: 13,
    fontWeight: '600',
  },
  periodTabLabelSelected: {
    color: colors.surfaceWhite,
  },
  dateNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing.md,
    marginBottom: spacing.lg,
  },
  dateNavButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.surfaceMutedIcon,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dateNavButtonDisabled: {
    opacity: 0.45,
  },
  dateNavLabelWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  dateNavLabel: {
    color: colors.inkPrimary,
    fontSize: 15,
    fontWeight: '600',
  },
  summaryCard: {
    backgroundColor: colors.brandGreenSoft,
    borderRadius: radius.card,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.md,
  },
  summaryLabel: {
    ...typography.earningsLabel,
    fontWeight: '500',
  },
  summaryTotal: {
    color: colors.inkPrimary,
    fontSize: 36,
    fontWeight: '800',
    marginTop: 4,
    marginBottom: spacing.lg,
    letterSpacing: -0.5,
  },
  statsRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  statColumn: {
    flex: 1,
    alignItems: 'center',
  },
  statIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.surfaceWhite,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.sm,
  },
  statValue: {
    color: colors.inkPrimary,
    fontSize: 16,
    fontWeight: '700',
  },
  statLabel: {
    ...typography.earningsLabel,
    fontWeight: '500',
    fontSize: 11,
    textAlign: 'center',
    marginTop: 2,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing.xl,
    marginBottom: spacing.md,
  },
  sectionTitle: {
    ...typography.headline,
    fontSize: 17,
  },
  seeAll: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  seeAllLabel: {
    color: colors.brandGreen,
    fontSize: 14,
    fontWeight: '600',
  },
  jobCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surfaceWhite,
    borderRadius: radius.card,
    paddingVertical: 14,
    paddingHorizontal: spacing.md,
    marginBottom: spacing.sm,
    shadowColor: colors.shadow,
    shadowOpacity: 1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  jobWhen: {
    width: 52,
  },
  jobDate: {
    color: colors.inkPrimary,
    fontSize: 13,
    fontWeight: '600',
  },
  jobTime: {
    ...typography.body,
    fontSize: 12,
    marginTop: 2,
  },
  jobRail: {
    width: StyleSheet.hairlineWidth,
    alignSelf: 'stretch',
    backgroundColor: colors.surfaceMutedIcon,
    marginRight: spacing.md,
    marginLeft: spacing.sm,
  },
  jobCopy: {
    flex: 1,
    paddingRight: spacing.sm,
  },
  jobTitle: {
    color: colors.inkPrimary,
    fontSize: 15,
    fontWeight: '700',
  },
  jobRoute: {
    ...typography.statusSubtext,
    marginTop: 2,
  },
  jobFare: {
    color: colors.inkPrimary,
    fontSize: 15,
    fontWeight: '700',
    marginRight: 4,
  },
  emptyJobs: {
    backgroundColor: colors.surfaceWhite,
    borderRadius: radius.card,
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.md,
    marginBottom: spacing.sm,
    shadowColor: colors.shadow,
    shadowOpacity: 1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  emptyJobsTitle: {
    color: colors.inkPrimary,
    fontSize: 15,
    fontWeight: '700',
  },
  emptyJobsBody: {
    ...typography.statusSubtext,
    marginTop: 4,
  },
  viewAllRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surfaceWhite,
    borderRadius: radius.card,
    paddingVertical: 14,
    paddingHorizontal: spacing.md,
    marginTop: spacing.sm,
    shadowColor: colors.shadow,
    shadowOpacity: 1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  viewAllIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: colors.surfaceMutedIcon,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
  },
  viewAllLabel: {
    flex: 1,
    color: colors.inkPrimary,
    fontSize: 15,
    fontWeight: '600',
  },
  payoutCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surfaceWhite,
    borderRadius: radius.card,
    paddingVertical: 14,
    paddingHorizontal: spacing.md,
    shadowColor: colors.shadow,
    shadowOpacity: 1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  payoutCopy: {
    flex: 1,
  },
  payoutTitle: {
    color: colors.inkPrimary,
    fontSize: 15,
    fontWeight: '700',
  },
  payoutSubtitle: {
    ...typography.statusSubtext,
    marginTop: 2,
  },
  payoutAmount: {
    color: colors.inkPrimary,
    fontSize: 15,
    fontWeight: '700',
  },
  loadingWrap: {
    flex: 1,
    paddingVertical: spacing.xl,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
