import { StyleSheet } from 'react-native';
import { COLORS, VARS } from '@/lib/constants';

const CARD_RADIUS = 16;
const BORDER = COLORS.background;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: VARS.xsmall,
    paddingTop: VARS.xxsmall,
    paddingBottom: VARS.xsmall,
    backgroundColor: COLORS.white,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  helpPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 22,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  helpPillText: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.text,
  },
  titleBlock: {
    paddingHorizontal: VARS.small,
    paddingBottom: VARS.small,
    backgroundColor: COLORS.white,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: COLORS.text,
  },
  subtitle: {
    marginTop: 4,
    fontSize: 15,
    color: COLORS.textSecondary,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: VARS.small,
    paddingTop: VARS.small,
    paddingBottom: VARS.medium,
  },
  sectionLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.text,
    marginBottom: VARS.xsmall,
  },
  timeWindowBlock: {
    marginBottom: VARS.medium,
  },
  segmentTrack: {
    flexDirection: 'row',
    backgroundColor: COLORS.background,
    borderRadius: 28,
    padding: 4,
    marginBottom: VARS.medium,
  },
  segmentButton: {
    flex: 1,
    borderRadius: 24,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentButtonActive: {
    backgroundColor: COLORS.primary,
  },
  segmentText: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.textSecondary,
  },
  segmentTextActive: {
    color: COLORS.white,
  },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: CARD_RADIUS,
    borderWidth: 1,
    borderColor: BORDER,
    padding: VARS.small,
    marginBottom: VARS.medium,
  },
  dateCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: VARS.xsmall,
  },
  dateIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: COLORS.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dateCopy: {
    flex: 1,
    minWidth: 0,
  },
  dateTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.text,
  },
  dateHint: {
    marginTop: 2,
    fontSize: 13,
    color: COLORS.textSecondary,
  },
  frequencyList: {
    gap: VARS.xsmall,
    marginBottom: VARS.medium,
  },
  frequencyCard: {
    backgroundColor: COLORS.white,
    borderRadius: CARD_RADIUS,
    borderWidth: 1.5,
    borderColor: BORDER,
    padding: VARS.small,
  },
  frequencyCardSelected: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.white,
  },
  frequencyTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: VARS.xxsmall,
  },
  frequencyTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.text,
  },
  frequencyTitleSelected: {
    color: COLORS.primary,
  },
  frequencyBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    backgroundColor: COLORS.background,
  },
  frequencyBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.primary,
  },
  frequencyDetail: {
    marginTop: 4,
    fontSize: 13,
    color: COLORS.textSecondary,
  },
  frequencyPriceRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 6,
  },
  frequencyPriceOriginal: {
    fontSize: 14,
    color: COLORS.textSecondary,
    textDecorationLine: 'line-through',
  },
  frequencyPriceDiscount: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.primary,
  },
  collectionHelperText: {
    fontSize: 13,
    color: COLORS.textSecondary,
    marginTop: -12,
    marginBottom: VARS.medium,
    lineHeight: 18,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: VARS.xsmall,
    paddingVertical: 10,
  },
  summaryIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: COLORS.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  summaryItemLabel: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: COLORS.text,
  },
  summaryItemPrice: {
    fontSize: 15,
    fontWeight: '600',
    color: COLORS.text,
  },
  summaryDivider: {
    height: 1,
    backgroundColor: BORDER,
    marginVertical: 4,
  },
  summaryTotalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 8,
  },
  summaryTotalLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.text,
  },
  summaryTotalValue: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.text,
  },
  summaryTotalAmounts: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  summaryOriginalValue: {
    fontSize: 13,
    color: COLORS.textSecondary,
    textDecorationLine: 'line-through',
    marginRight: 8,
  },
  summarySavingsText: {
    marginTop: 6,
    fontSize: 13,
    color: COLORS.primary,
  },
  addressCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: VARS.xsmall,
  },
  addressCopy: {
    flex: 1,
    minWidth: 0,
  },
  addressText: {
    fontSize: 15,
    fontWeight: '600',
    color: COLORS.text,
  },
  addressMissing: {
    fontSize: 14,
    color: COLORS.accent,
  },
  changeLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  changeLinkText: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.primary,
  },
  paymentRow: {
    flexDirection: 'row',
    gap: VARS.xsmall,
  },
  paymentCard: {
    flex: 1,
    borderRadius: CARD_RADIUS,
    borderWidth: 1.5,
    borderColor: BORDER,
    backgroundColor: COLORS.white,
    padding: VARS.xsmall,
  },
  paymentCardSelected: {
    borderColor: COLORS.primary,
  },
  paymentCardDisabled: {
    opacity: 0.55,
    backgroundColor: COLORS.background,
  },
  paymentCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  paymentIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: COLORS.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  paymentRadio: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: COLORS.textSecondary,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
  },
  paymentRadioSelected: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.primary,
  },
  paymentTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.text,
  },
  paymentSubtitle: {
    marginTop: 2,
    fontSize: 12,
    lineHeight: 16,
    color: COLORS.textSecondary,
  },
  comingSoon: {
    marginTop: 6,
    alignSelf: 'flex-start',
    backgroundColor: COLORS.background,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  comingSoonText: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.textSecondary,
  },
  stripeQuoteBox: {
    marginTop: VARS.small,
    marginBottom: VARS.small,
    backgroundColor: COLORS.white,
    borderRadius: CARD_RADIUS,
    borderWidth: 1,
    borderColor: BORDER,
    padding: VARS.xsmall,
  },
  currencyRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 8,
  },
  currencyChip: {
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: COLORS.background,
  },
  currencyChipSelected: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.primary,
  },
  currencyChipText: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.text,
  },
  currencyChipTextSelected: {
    color: COLORS.white,
  },
  stripeQuoteLine: {
    fontSize: 13,
    color: COLORS.textSecondary,
    marginBottom: 4,
  },
  stripeQuoteAmount: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.text,
    marginBottom: 4,
  },
  noItemsNotice: {
    backgroundColor: COLORS.amberLight,
    borderRadius: VARS.xsmall,
    padding: VARS.small,
    marginBottom: VARS.small,
  },
  noItemsText: {
    fontSize: 13,
    color: COLORS.amberDark,
    lineHeight: 18,
  },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: VARS.small,
    paddingHorizontal: VARS.small,
    paddingTop: VARS.small,
    backgroundColor: COLORS.white,
    borderTopWidth: 1,
    borderTopColor: BORDER,
  },
  totalLabel: {
    fontSize: 13,
    color: COLORS.textSecondary,
    marginBottom: 2,
  },
  totalValue: {
    fontSize: 26,
    fontWeight: '700',
    color: COLORS.text,
  },
  continueButton: {
    flex: 1,
    maxWidth: 230,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: COLORS.primary,
    borderRadius: 28,
    paddingVertical: 16,
    paddingHorizontal: VARS.small,
  },
  continueButtonDisabled: {
    opacity: 0.4,
  },
  continueButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.white,
  },
});
