import { StyleSheet } from "react-native";
import { COLORS, VARS } from "@/lib/constants";

export const styles = StyleSheet.create({
  content: {
    padding: VARS.medium,
    gap: VARS.small,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: VARS.small,
  },
  headerOptionsButton: {
    marginRight: VARS.small,
    paddingHorizontal: 4,
    paddingVertical: 4,
  },
  headerOptionsDots: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
  },
  headerDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: COLORS.white,
  },
  title: {
    fontSize: 24,
    fontWeight: "700",
    marginBottom: VARS.small,
    color: COLORS.text,
  },
  newBookingButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 8,
    paddingHorizontal: VARS.small,
    borderRadius: VARS.xsmall,
  },
  newBookingButtonText: {
    color: COLORS.white,
    fontWeight: "600",
  },
  profileBanner: {
    backgroundColor: COLORS.white,
    padding: VARS.medium,
    borderRadius: VARS.small,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
    marginBottom: VARS.small,
  },
  bannerTitle: {
    fontSize: 18,
    fontWeight: "600",
    marginBottom: VARS.xsmall,
    color: COLORS.primary,
  },
  bannerSubtitle: {
    fontSize: 14,
    color: COLORS.textSecondary,
    lineHeight: 20,
  },
  card: {
    backgroundColor: COLORS.white,
    padding: VARS.medium,
    borderRadius: VARS.small,
    marginBottom: VARS.small,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: VARS.xsmall,
  },
  cardDate: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.text,
  },
  statusBadge: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 20,
  },
  statusText: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.white,
  },
  cardPrice: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.text,
    marginBottom: 4,
  },
  cardNote: {
    fontSize: 14,
    color: COLORS.textSecondary,
  },
  cardWindow: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.text,
    marginBottom: 4,
  },
  cardLocation: {
    fontSize: 14,
    color: COLORS.textSecondary,
    marginBottom: 4,
  },
  cardSummary: {
    fontSize: 14,
    color: COLORS.text,
    marginBottom: 2,
  },
  cardTotal: {
    fontSize: 15,
    fontWeight: "600",
    color: COLORS.primary,
  },
  placeholderCard: {
    backgroundColor: "#F0F4F8",
    padding: VARS.medium,
    borderRadius: VARS.small,
    marginTop: VARS.medium,
  },
  placeholderText: {
    fontSize: 14,
    color: COLORS.textSecondary,
    textAlign: "center",
  },
  loadingState: {
    alignItems: "center",
    paddingVertical: VARS.large,
  },
  loadingText: {
    marginTop: VARS.xsmall,
    color: COLORS.textSecondary,
  },
  errorState: {
    backgroundColor: "#FFEBEE",
    padding: VARS.medium,
    borderRadius: VARS.small,
    gap: VARS.xsmall,
  },
  errorText: {
    color: COLORS.error,
    fontSize: 14,
  },
  retryButton: {
    alignSelf: "flex-start",
    paddingHorizontal: VARS.small,
    paddingVertical: 6,
    backgroundColor: COLORS.primary,
    borderRadius: VARS.xsmall,
  },
  retryButtonText: {
    color: COLORS.white,
    fontWeight: "600",
  },
  emptyState: {
    backgroundColor: "#E8F5E9",
    padding: VARS.medium,
    borderRadius: VARS.small,
    alignItems: "center",
    gap: VARS.xsmall,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: COLORS.text,
  },
  emptySubtitle: {
    fontSize: 14,
    textAlign: "center",
    color: COLORS.textSecondary,
  },
  emptyAction: {
    marginTop: VARS.xsmall,
    paddingHorizontal: VARS.medium,
    paddingVertical: 8,
    backgroundColor: COLORS.primary,
    borderRadius: VARS.xsmall,
  },
  emptyActionText: {
    color: COLORS.white,
    fontWeight: "600",
  },
  statusRow: {
    marginTop: VARS.xsmall,
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 8,
  },
  paymentStatusContainer: {
    marginTop: VARS.xsmall,
    alignItems: "flex-start",
  },
  paymentStatusBadge: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 20,
  },
  paymentStatusText: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.white,
  },
  paymentActionsRow: {
    marginTop: VARS.small,
    flexDirection: "row",
    gap: 8,
  },
  retryPaymentButton: {
    flex: 1,
    backgroundColor: COLORS.primary,
    paddingVertical: 10,
    paddingHorizontal: VARS.medium,
    borderRadius: VARS.xsmall,
    alignItems: "center",
    justifyContent: "center",
  },
  retryPaymentButtonWithVerify: {
    flex: 1,
  },
  retryPaymentButtonText: {
    color: COLORS.white,
    fontWeight: "600",
    fontSize: 14,
  },
  verifyPaymentButton: {
    flex: 1,
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: COLORS.primary,
    paddingVertical: 10,
    paddingHorizontal: VARS.medium,
    borderRadius: VARS.xsmall,
    alignItems: "center",
    justifyContent: "center",
  },
  verifyPaymentButtonText: {
    color: COLORS.primary,
    fontWeight: "600",
    fontSize: 14,
  },
  deleteIconButton: {
    padding: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  deleteIcon: {
    fontSize: 20,
    fontWeight: "600",
    color: COLORS.error,
  },
  subscriptionSection: {
    marginBottom: VARS.medium,
  },
  subscriptionSectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: COLORS.text,
    marginBottom: VARS.xsmall,
  },
  subscriptionCard: {
    backgroundColor: COLORS.white,
    padding: VARS.medium,
    borderRadius: VARS.small,
    marginBottom: VARS.small,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  subscriptionCardHeader: {
    fontSize: 16,
    fontWeight: "700",
    color: COLORS.text,
    marginBottom: VARS.xsmall,
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  detailLabel: {
    fontSize: 14,
    color: COLORS.textSecondary,
  },
  detailValue: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.text,
  },
  subscriptionStatusBadge: {
    alignSelf: "flex-start",
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 20,
    marginTop: VARS.xsmall,
  },
  subscriptionLoadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: VARS.xsmall,
    paddingVertical: VARS.small,
  },
  subscriptionLoadingText: {
    fontSize: 14,
    color: COLORS.textSecondary,
  },
  subscriptionEmptyCard: {
    backgroundColor: "#E8F5E9",
    padding: VARS.medium,
    borderRadius: VARS.small,
    alignItems: "center",
    gap: VARS.xsmall,
  },
  subscriptionEmptyTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.text,
    textAlign: "center",
  },
  subscriptionEmptySubtitle: {
    fontSize: 14,
    color: COLORS.textSecondary,
    textAlign: "center",
  },
  subscriptionEmptyCta: {
    marginTop: VARS.xsmall,
    paddingHorizontal: VARS.medium,
    paddingVertical: 10,
    backgroundColor: COLORS.primary,
    borderRadius: VARS.xsmall,
  },
  subscriptionEmptyCtaText: {
    color: COLORS.white,
    fontWeight: "600",
    fontSize: 14,
  },
  paymentBannerOverdue: {
    backgroundColor: "#FFF3E0",
    paddingVertical: VARS.xsmall,
    paddingHorizontal: VARS.small,
    borderRadius: VARS.xsmall,
    marginTop: VARS.xsmall,
    borderLeftWidth: 4,
    borderLeftColor: COLORS.accent,
  },
  paymentBannerInitiated: {
    backgroundColor: "#FFF8E1",
    paddingVertical: VARS.xsmall,
    paddingHorizontal: VARS.small,
    borderRadius: VARS.xsmall,
    marginTop: VARS.xsmall,
    borderLeftWidth: 4,
    borderLeftColor: COLORS.accent,
  },
  paymentBannerPaid: {
    backgroundColor: "#E8F5E9",
    paddingVertical: VARS.xsmall,
    paddingHorizontal: VARS.small,
    borderRadius: VARS.xsmall,
    marginTop: VARS.xsmall,
  },
  paymentBannerFailed: {
    backgroundColor: "#FFEBEE",
    paddingVertical: VARS.xsmall,
    paddingHorizontal: VARS.small,
    borderRadius: VARS.xsmall,
    marginTop: VARS.xsmall,
    borderLeftWidth: 4,
    borderLeftColor: COLORS.error,
  },
  paymentBannerText: {
    fontSize: 13,
    color: COLORS.text,
    fontWeight: "500",
  },
  subscriptionActionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: VARS.small,
    marginTop: VARS.small,
  },
  completePaymentButton: {
    flex: 1,
    backgroundColor: COLORS.primary,
    paddingVertical: 10,
    paddingHorizontal: VARS.medium,
    borderRadius: VARS.xsmall,
    alignItems: "center",
    justifyContent: "center",
  },
  completePaymentButtonText: {
    color: COLORS.white,
    fontWeight: "600",
    fontSize: 14,
  },
  cancelSubscriptionButton: {
    marginTop: VARS.small,
    paddingVertical: 10,
    paddingHorizontal: VARS.medium,
    borderRadius: VARS.xsmall,
    borderWidth: 1,
    borderColor: COLORS.error,
    alignItems: "center",
    justifyContent: "center",
  },
  cancelSubscriptionButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.error,
  },
});
