import { COLORS, VARS } from "@/lib/constants";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    scrollView: {
        flex: 1,
    },
    scrollContent: {
        paddingBottom: VARS.small,
    },
    content: {
        padding: VARS.small,
    },
    sectionTitle: {
        fontSize: VARS.medium + 4,
        fontWeight: '600',
        color: COLORS.text,
        marginBottom: VARS.small,
        marginTop: VARS.xxsmall,
    },
    binCard: {
        backgroundColor: COLORS.white,
        borderRadius: VARS.xsmall,
        padding: VARS.small,
        marginBottom: VARS.small,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    binInfo: {
        flex: 1,
        minWidth: 0,
        marginRight: VARS.xsmall,
    },
    binName: {
        fontSize: VARS.small,
        fontWeight: '600',
        color: COLORS.text,
        marginBottom: VARS.xxsmall / 2,
    },
    binPrice: {
        fontSize: VARS.xsmall + 2,
        color: COLORS.textSecondary,
    },
    binInfoLink: {
        fontSize: VARS.xsmall + 2,
        color: COLORS.primary,
        textDecorationLine: 'underline',
    },
    binInfoStandaloneContainer: {
        marginTop: VARS.xxsmall,
        marginBottom: VARS.small,
    },
    counter: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    counterButton: {
        backgroundColor: COLORS.primary,
        width: VARS.medium + 4,
        height: VARS.medium + 4,
        borderRadius: VARS.small + 2,
        justifyContent: 'center',
        alignItems: 'center',
    },
    counterButtonText: {
        color: COLORS.white,
        fontSize: VARS.small + 4,
        fontWeight: '600',
    },
    counterValue: {
        fontSize: VARS.small + 2,
        fontWeight: '600',
        color: COLORS.text,
        marginHorizontal: VARS.small,
        minWidth: VARS.medium + 4,
        textAlign: 'center',
    },
    footer: {
        paddingHorizontal: VARS.small,
        paddingTop: VARS.xsmall,
        paddingBottom: VARS.large,
        backgroundColor: COLORS.background,
        borderTopWidth: 1,
        borderTopColor: '#E8E8E8',
    },
    totalCard: {
        backgroundColor: COLORS.primary,
        borderRadius: VARS.xsmall,
        padding: VARS.small + 4,
        marginBottom: VARS.xsmall,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    totalLabel: {
        fontSize: VARS.small + 2,
        fontWeight: '600',
        color: COLORS.white,
    },
    totalValue: {
        fontSize: VARS.medium + 4,
        fontWeight: 'bold',
        color: COLORS.white,
    },
    placeholderText: {
        color: COLORS.textSecondary,
        fontSize: VARS.xsmall + 2,
        fontStyle: 'italic',
        marginBottom: VARS.small,
    },
    submitButton: {
        backgroundColor: COLORS.primary,
        borderRadius: VARS.xxsmall,
        padding: VARS.small,
        alignItems: 'center',
    },
    submitButtonText: {
        color: COLORS.white,
        fontSize: VARS.small,
        fontWeight: '600',
    },
    bottomSheetOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: -70,
        backgroundColor: 'rgba(0,0,0,0.4)',
        justifyContent: 'flex-end',
    },
    bottomSheetContainer: {
        backgroundColor: COLORS.white,
        borderTopLeftRadius: VARS.medium,
        borderTopRightRadius: VARS.medium,
        paddingHorizontal: VARS.medium,
        paddingTop: VARS.small,
        paddingBottom: VARS.small,
    },
    bottomSheetHandle: {
        alignSelf: 'center',
        width: 40,
        height: 4,
        borderRadius: 2,
        backgroundColor: COLORS.textSecondary,
        marginBottom: VARS.small,
        opacity: 0.4,
    },
    bottomSheetTitle: {
        fontSize: VARS.medium,
        fontWeight: '700',
        color: COLORS.text,
        marginBottom: VARS.small,
        textAlign: 'center',
    },
    bottomSheetRow: {
        marginBottom: VARS.small,
    },
    bottomSheetRowTitle: {
        fontSize: VARS.small + 2,
        fontWeight: '600',
        color: COLORS.text,
        marginBottom: VARS.xxsmall / 2,
    },
    bottomSheetRowSubtitle: {
        fontSize: VARS.xsmall + 2,
        color: COLORS.textSecondary,
        lineHeight: 18,
    },
    bottomSheetCloseButton: {
        marginTop: VARS.small,
        alignSelf: 'center',
        paddingVertical: VARS.xsmall,
        paddingHorizontal: VARS.large,
        borderRadius: VARS.xsmall,
        backgroundColor: COLORS.primary,
    },
    bottomSheetCloseButtonText: {
        fontSize: VARS.small,
        fontWeight: '600',
        color: COLORS.white,
    },
});
