import { StyleSheet } from "react-native";
import { COLORS, VARS } from "@/lib/constants";
import { MY_BOOKINGS_DASHBOARD_TITLE_COLOR, MY_BOOKINGS_PAGE_BG } from "./my-bookings-screen.utils";

export const SCREEN_PADDING_H = 16;

export const styles = StyleSheet.create({
  scrollRoot: {
    flex: 1,
    backgroundColor: MY_BOOKINGS_PAGE_BG,
  },
  scrollInner: {
    paddingHorizontal: SCREEN_PADDING_H,
    paddingTop: 16,
    paddingBottom: VARS.large,
  },
  pageHeaderBlock: {
    marginBottom: 20,
  },
  dashboardTitle: {
    fontSize: 26,
    fontWeight: "800",
    color: MY_BOOKINGS_DASHBOARD_TITLE_COLOR,
    letterSpacing: -0.4,
    lineHeight: 32,
    marginBottom: 8,
  },
  dashboardSubtitle: {
    fontSize: 14,
    lineHeight: 21,
    color: COLORS.textSecondary,
    fontWeight: "400",
    flexShrink: 1,
  },
  sectionBlock: {
    marginTop: 26,
  },
  sectionBlockFirst: {
    marginTop: 8,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  sectionCapsLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: COLORS.textSecondary,
    letterSpacing: 1.2,
    marginBottom: 12,
  },
  sectionCapsLabelInline: {
    flex: 1,
    marginBottom: 0,
    marginRight: 8,
  },
  schedulePill: {
    backgroundColor: COLORS.primary,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 22,
  },
  schedulePillText: {
    fontSize: 13,
    fontWeight: "800",
    color: COLORS.white,
    letterSpacing: 0.2,
  },
  headerOptionsButton: {
    marginRight: VARS.small,
    paddingHorizontal: 4,
    paddingVertical: 4,
  },
  headerOptionsDots: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
  },
  headerDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: COLORS.white,
  },
  profileBanner: {
    backgroundColor: COLORS.white,
    paddingVertical: VARS.medium,
    paddingHorizontal: SCREEN_PADDING_H,
    borderRadius: VARS.small,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
    marginBottom: VARS.small,
  },
  bannerTitle: {
    fontSize: 18,
    fontWeight: "600",
    marginBottom: VARS.xsmall,
    color: COLORS.primary,
  },
  bannerSubtitle: {
    fontSize: 14,
    color: COLORS.textSecondary,
    lineHeight: 20,
  },
  card: {
    backgroundColor: COLORS.white,
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: VARS.small,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: VARS.xsmall,
  },
  cardDate: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.text,
  },
  bookingCardTitleRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 8,
    marginBottom: 2,
  },
  bookingListStatusBadge: {
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 10,
    flexShrink: 0,
  },
  bookingListStatusText: {
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.6,
  },
  bookingCardMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 8,
  },
  bookingCardMetaIcon: {
    fontSize: 14,
    lineHeight: 18,
  },
  cardPrice: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.text,
    marginBottom: 4,
  },
  cardNote: {
    fontSize: 14,
    color: COLORS.textSecondary,
  },
  cardWindow: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.text,
    marginBottom: 4,
  },
  cardLocation: {
    fontSize: 14,
    color: COLORS.textSecondary,
    marginBottom: 4,
  },
  cardSummary: {
    fontSize: 14,
    color: COLORS.text,
    marginBottom: 2,
  },
  cardTotal: {
    fontSize: 15,
    fontWeight: "600",
    color: COLORS.primary,
  },
  placeholderCard: {
    backgroundColor: "#F0F4F8",
    padding: VARS.medium,
    borderRadius: VARS.small,
    marginTop: VARS.medium,
  },
  placeholderText: {
    fontSize: 14,
    color: COLORS.textSecondary,
    textAlign: "center",
  },
  loadingState: {
    alignItems: "center",
    paddingVertical: VARS.large,
  },
  loadingText: {
    marginTop: VARS.xsmall,
    color: COLORS.textSecondary,
  },
  errorState: {
    backgroundColor: "#FFEBEE",
    paddingVertical: VARS.medium,
    paddingHorizontal: SCREEN_PADDING_H,
    borderRadius: VARS.small,
    gap: VARS.xsmall,
  },
  errorText: {
    color: COLORS.error,
    fontSize: 14,
  },
  retryButton: {
    alignSelf: "flex-start",
    paddingHorizontal: VARS.small,
    paddingVertical: 6,
    backgroundColor: COLORS.primary,
    borderRadius: VARS.xsmall,
  },
  retryButtonText: {
    color: COLORS.white,
    fontWeight: "600",
  },
  emptyState: {
    backgroundColor: "#E8F5E9",
    paddingVertical: VARS.medium,
    paddingHorizontal: SCREEN_PADDING_H,
    borderRadius: VARS.small,
    alignItems: "center",
    gap: VARS.xsmall,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: COLORS.text,
  },
  emptySubtitle: {
    fontSize: 14,
    textAlign: "center",
    color: COLORS.textSecondary,
  },
  emptyAction: {
    marginTop: VARS.xsmall,
    paddingHorizontal: VARS.medium,
    paddingVertical: 8,
    backgroundColor: COLORS.primary,
    borderRadius: VARS.xsmall,
  },
  emptyActionText: {
    color: COLORS.white,
    fontWeight: "600",
  },
  statusRow: {
    marginTop: VARS.xsmall,
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 8,
  },
  paymentStatusContainer: {
    marginTop: VARS.xsmall,
    alignItems: "flex-start",
  },
  paymentStatusBadge: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 20,
  },
  paymentStatusText: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.white,
  },
  paymentActionsRow: {
    marginTop: VARS.small,
    flexDirection: "row",
    gap: 8,
  },
  retryPaymentButton: {
    flex: 1,
    backgroundColor: COLORS.primary,
    paddingVertical: 10,
    paddingHorizontal: VARS.medium,
    borderRadius: VARS.xsmall,
    alignItems: "center",
    justifyContent: "center",
  },
  retryPaymentButtonWithVerify: {
    flex: 1,
  },
  retryPaymentButtonText: {
    color: COLORS.white,
    fontWeight: "600",
    fontSize: 14,
  },
  verifyPaymentButton: {
    flex: 1,
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: COLORS.primary,
    paddingVertical: 10,
    paddingHorizontal: VARS.medium,
    borderRadius: VARS.xsmall,
    alignItems: "center",
    justifyContent: "center",
  },
  verifyPaymentButtonText: {
    color: COLORS.primary,
    fontWeight: "600",
    fontSize: 14,
  },
  deleteIconButton: {
    padding: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  deleteIcon: {
    fontSize: 20,
    fontWeight: "600",
    color: COLORS.error,
  },
  subscriptionCard: {
    backgroundColor: COLORS.white,
    paddingVertical: 18,
    paddingHorizontal: SCREEN_PADDING_H,
    borderRadius: VARS.small,
    marginBottom: VARS.small,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  subscriptionCardHeader: {
    fontSize: 16,
    fontWeight: "700",
    color: COLORS.text,
    marginBottom: VARS.xsmall,
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  detailLabel: {
    fontSize: 14,
    color: COLORS.textSecondary,
  },
  detailValue: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.text,
  },
  subscriptionStatusBadge: {
    alignSelf: "flex-start",
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 20,
    marginTop: VARS.xsmall,
  },
  subscriptionLoadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: VARS.xsmall,
    paddingVertical: VARS.small,
  },
  subscriptionLoadingText: {
    fontSize: 14,
    color: COLORS.textSecondary,
  },
  subscriptionEmptyCard: {
    backgroundColor: "#E8F5E9",
    paddingVertical: VARS.medium,
    paddingHorizontal: SCREEN_PADDING_H,
    borderRadius: VARS.small,
    alignItems: "center",
    gap: VARS.xsmall,
  },
  subscriptionEmptyTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.text,
    textAlign: "center",
  },
  subscriptionEmptySubtitle: {
    fontSize: 14,
    color: COLORS.textSecondary,
    textAlign: "center",
  },
  subscriptionEmptyCta: {
    marginTop: VARS.xsmall,
    paddingHorizontal: VARS.medium,
    paddingVertical: 10,
    backgroundColor: COLORS.primary,
    borderRadius: VARS.xsmall,
  },
  subscriptionEmptyCtaText: {
    color: COLORS.white,
    fontWeight: "600",
    fontSize: 14,
  },
  paymentBannerOverdue: {
    backgroundColor: "#FFF3E0",
    paddingVertical: VARS.xsmall,
    paddingHorizontal: VARS.small,
    borderRadius: VARS.xsmall,
    marginTop: VARS.xsmall,
    borderLeftWidth: 4,
    borderLeftColor: COLORS.accent,
  },
  paymentBannerInitiated: {
    backgroundColor: "#FFF8E1",
    paddingVertical: VARS.xsmall,
    paddingHorizontal: VARS.small,
    borderRadius: VARS.xsmall,
    marginTop: VARS.xsmall,
    borderLeftWidth: 4,
    borderLeftColor: COLORS.accent,
  },
  paymentBannerPaid: {
    backgroundColor: "#E8F5E9",
    paddingVertical: VARS.xsmall,
    paddingHorizontal: VARS.small,
    borderRadius: VARS.xsmall,
    marginTop: VARS.xsmall,
  },
  paymentBannerFailed: {
    backgroundColor: "#FFEBEE",
    paddingVertical: VARS.xsmall,
    paddingHorizontal: VARS.small,
    borderRadius: VARS.xsmall,
    marginTop: VARS.xsmall,
    borderLeftWidth: 4,
    borderLeftColor: COLORS.error,
  },
  paymentBannerText: {
    fontSize: 13,
    color: COLORS.text,
    fontWeight: "500",
  },
  subscriptionActionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: VARS.small,
    marginTop: VARS.small,
  },
  completePaymentButton: {
    flex: 1,
    backgroundColor: COLORS.primary,
    paddingVertical: 10,
    paddingHorizontal: VARS.medium,
    borderRadius: VARS.xsmall,
    alignItems: "center",
    justifyContent: "center",
  },
  completePaymentButtonText: {
    color: COLORS.white,
    fontWeight: "600",
    fontSize: 14,
  },
  cancelSubscriptionButton: {
    marginTop: VARS.small,
    paddingVertical: 10,
    paddingHorizontal: VARS.medium,
    borderRadius: VARS.xsmall,
    borderWidth: 1,
    borderColor: COLORS.error,
    alignItems: "center",
    justifyContent: "center",
  },
  cancelSubscriptionButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.error,
  },
  bookingCardTouchable: {
    flexDirection: "row",
    alignItems: "center",
    minHeight: 56,
  },
  bookingCardMain: {
    flex: 1,
    minWidth: 0,
  },
  bookingCardType: {
    flexShrink: 1,
    fontSize: 16,
    fontWeight: "700",
    color: COLORS.text,
    letterSpacing: -0.15,
    lineHeight: 22,
  },
  bookingCardTitleMuted: {
    color: "#616161",
  },
  oneTimeStatusCaps: {
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.7,
    marginTop: 6,
  },
  bookingCardNext: {
    flexShrink: 1,
    fontSize: 13,
    lineHeight: 18,
    color: COLORS.textSecondary,
    fontWeight: "500",
  },
  bookingCardChevron: {
    fontSize: 22,
    fontWeight: "300",
    color: "#9E9E9E",
    marginLeft: 4,
    alignSelf: "center",
  },
  bookingCardMuted: {
    opacity: 0.65,
  },
});
