import { StyleSheet } from 'react-native';
import { colors, radius, spacing, typography } from '@platform/shared-theme';

const cardBorder = '#EEF1F4';
const pageBg = '#F7F8FA';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.surfaceWhite,
  },
  scrollRoot: {
    flex: 1,
    backgroundColor: pageBg,
  },
  scrollInner: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xl,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  backButton: {
    width: 44,
    height: 44,
    marginLeft: -spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: colors.brandGreen,
    letterSpacing: -0.4,
    lineHeight: 34,
    marginBottom: spacing.xs,
  },
  pageSubtitle: {
    ...typography.body,
    fontSize: 14,
    lineHeight: 21,
    marginBottom: spacing.lg,
  },
  itemCard: {
    backgroundColor: colors.surfaceWhite,
    borderRadius: radius.card,
    borderWidth: 1,
    borderColor: cardBorder,
    padding: spacing.md,
    marginBottom: spacing.md,
    flexDirection: 'row',
    gap: spacing.md,
  },
  imageWrap: {
    width: 72,
    height: 72,
    borderRadius: 12,
    backgroundColor: colors.brandGreenSoft,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  image: {
    width: 72,
    height: 72,
  },
  itemCopy: {
    flex: 1,
    minWidth: 0,
  },
  itemName: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.inkPrimary,
    marginBottom: 2,
  },
  itemDescription: {
    ...typography.body,
    fontSize: 13,
    lineHeight: 18,
    marginBottom: spacing.sm,
  },
  itemFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  itemPrice: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.brandGreen,
  },
  itemActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  stepper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: cardBorder,
    borderRadius: radius.pill,
    backgroundColor: colors.surfaceWhite,
  },
  stepperBtn: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperCount: {
    minWidth: 22,
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '700',
    color: colors.inkPrimary,
  },
  deleteBtn: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  empty: {
    ...typography.body,
    textAlign: 'center',
    paddingVertical: spacing.xl,
  },
  promoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: spacing.md,
  },
  promoHeaderText: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.inkPrimary,
  },
  promoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  promoInput: {
    flex: 1,
  },
  applyButton: {
    backgroundColor: colors.brandGreen,
    borderRadius: radius.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: 12,
  },
  applyButtonText: {
    ...typography.button,
    fontSize: 14,
    color: colors.surfaceWhite,
  },
  sectionLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.inkPrimary,
    marginBottom: spacing.sm,
    marginTop: spacing.sm,
  },
  summaryCard: {
    backgroundColor: colors.surfaceWhite,
    borderRadius: radius.card,
    borderWidth: 1,
    borderColor: cardBorder,
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  summaryLabel: {
    ...typography.body,
    fontSize: 14,
  },
  summaryValue: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.inkPrimary,
  },
  summaryDivider: {
    height: 1,
    backgroundColor: cardBorder,
    marginBottom: spacing.sm,
  },
  summaryTotalLabel: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.inkPrimary,
  },
  summaryTotalValue: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.brandGreen,
  },
  addressCard: {
    backgroundColor: colors.surfaceWhite,
    borderRadius: radius.card,
    borderWidth: 1,
    borderColor: cardBorder,
    padding: spacing.md,
    marginBottom: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  addressIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors.brandGreenSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addressCopy: {
    flex: 1,
    minWidth: 0,
  },
  addressText: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.inkPrimary,
  },
  addressMissing: {
    fontSize: 14,
    color: colors.signalRed,
  },
  changeLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  changeLinkText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.brandGreen,
  },
  disclaimer: {
    ...typography.body,
    fontSize: 13,
    lineHeight: 18,
    marginBottom: spacing.md,
  },
  paymentRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.lg,
  },
  paymentCard: {
    flex: 1,
    borderRadius: radius.card,
    borderWidth: 1.5,
    borderColor: cardBorder,
    backgroundColor: colors.surfaceWhite,
    padding: spacing.sm,
  },
  paymentCardSelected: {
    borderColor: colors.brandGreen,
  },
  paymentCardDisabled: {
    opacity: 0.55,
    backgroundColor: pageBg,
  },
  paymentCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  paymentIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: pageBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  paymentRadio: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: colors.inkSecondary,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceWhite,
  },
  paymentRadioSelected: {
    borderColor: colors.brandGreen,
    backgroundColor: colors.brandGreen,
  },
  paymentTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.inkPrimary,
  },
  paymentSubtitle: {
    marginTop: 2,
    fontSize: 12,
    lineHeight: 16,
    color: colors.inkSecondary,
  },
  comingSoon: {
    marginTop: 6,
    alignSelf: 'flex-start',
    backgroundColor: pageBg,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  comingSoonText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.inkSecondary,
  },
  checkoutButton: {
    backgroundColor: colors.brandGreen,
    borderRadius: radius.pill,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  checkoutButtonDisabled: {
    opacity: 0.45,
  },
  checkoutButtonText: {
    ...typography.button,
    color: colors.surfaceWhite,
  },
});
